# Generated by Django 3.2.7 on 2021-10-26 22:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('notes', models.TextField(blank=True, max_length=200, null=True)),
                ('day', models.DateField()),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Event_assigned_by', to='employees.employees')),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='EventsHasEmployees',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='events.events')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employees')),
            ],
            options={
                'db_table': 'events_has_employees',
                'unique_together': {('event', 'employee')},
            },
        ),
        migrations.AddField(
            model_name='events',
            name='assigned_to',
            field=models.ManyToManyField(through='events.EventsHasEmployees', to='employees.Employees'),
        ),
    ]
