# Generated by Django 3.2.7 on 2021-10-27 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Event'},
        ),
        migrations.RemoveField(
            model_name='events',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='events',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='events',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='events',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='events',
            name='day',
            field=models.DateField(verbose_name='Day of Event'),
        ),
        migrations.AlterField(
            model_name='events',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Ends'),
        ),
        migrations.AlterField(
            model_name='events',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Begins'),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterModelTable(
            name='events',
            table=None,
        ),
        migrations.DeleteModel(
            name='EventsHasEmployees',
        ),
    ]
