# Generated by Django 3.2.7 on 2021-10-09 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(choices=[('1', 'Manager'), ('2', 'Assistant Manager'), ('3', 'Supervisor'), ('4', 'Server'), ('5', 'Busser'), ('6', 'Bartender'), ('7', 'Expo'), ('8', 'Host'), ('9', 'Barback'), ('20', 'Chef'), ('21', 'Sous Chef'), ('22', 'Pantry'), ('23', 'Line Cook'), ('24', 'Grill Cook'), ('25', 'Prep Cook'), ('26', 'Fry Cook'), ('27', 'Dishwasher')])),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee #', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.position')),
            ],
        ),
    ]
