# Generated by Django 3.2.7 on 2021-11-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
