# Generated by Django 3.2.7 on 2021-10-26 08:28

from django.db import migrations, models
import django.utils.timezone
import employees.validators


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='first_name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='employees',
            name='last_name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='employees',
            name='login_num',
            field=models.CharField(help_text='4 digit pin', max_length=4, unique=True, validators=[employees.validators.validate_employee_number], verbose_name='Employee #'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='employees',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='username',
            field=models.CharField(max_length=45),
        ),
    ]
