# Generated by Django 3.2.7 on 2021-10-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Employee #',
            field=models.IntegerField(help_text='4 number pin', unique=True),
        ),
    ]
