# Generated by Django 3.2.7 on 2021-10-26 11:42

from django.db import migrations, models
import employees.validators


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20211026_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='login_num',
            field=models.CharField(help_text='4 digit pin', max_length=4, validators=[employees.validators.validate_employee_number], verbose_name='Employee #'),
        ),
    ]
