# Generated by Django 3.2.7 on 2021-10-09 09:48

from django.db import migrations, models
import employees.validators


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_employee #'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Employee #',
            field=models.IntegerField(help_text='4 number pin', unique=True, validators=[employees.validators.validate_employee_number]),
        ),
    ]
