# Generated by Django 3.2.7 on 2021-10-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_employee #'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Employee #',
            new_name='emp_num',
        ),
    ]
