# Generated by Django 3.2.7 on 2021-10-15 14:17

from django.db import migrations, models
import employees.validators


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_auto_20211010_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_num',
            field=models.CharField(help_text='4 digit pin', max_length=4, validators=[employees.validators.validate_employee_number], verbose_name='Employee #'),
        ),
    ]
