# Generated by Django 3.2.7 on 2021-10-26 22:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Unacceptable'), (2, 'Needs Improvement'), (3, 'Satisfactory'), (4, 'Above Average'), (5, 'Exceptional')])),
                ('grooming', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Unacceptable'), (2, 'Needs Improvement'), (3, 'Satisfactory'), (4, 'Above Average'), (5, 'Exceptional')])),
                ('punctuality', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Unacceptable'), (2, 'Needs Improvement'), (3, 'Satisfactory'), (4, 'Above Average'), (5, 'Exceptional')])),
                ('attire', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Unacceptable'), (2, 'Needs Improvement'), (3, 'Satisfactory'), (4, 'Above Average'), (5, 'Exceptional')])),
                ('teamwork', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Unacceptable'), (2, 'Needs Improvement'), (3, 'Satisfactory'), (4, 'Above Average'), (5, 'Exceptional')])),
                ('initiative', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Unacceptable'), (2, 'Needs Improvement'), (3, 'Satisfactory'), (4, 'Above Average'), (5, 'Exceptional')])),
                ('service', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Unacceptable'), (2, 'Needs Improvement'), (3, 'Satisfactory'), (4, 'Above Average'), (5, 'Exceptional')])),
                ('quality', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Unacceptable'), (2, 'Needs Improvement'), (3, 'Satisfactory'), (4, 'Above Average'), (5, 'Exceptional')])),
                ('productivity', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Unacceptable'), (2, 'Needs Improvement'), (3, 'Satisfactory'), (4, 'Above Average'), (5, 'Exceptional')])),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employees')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
