# Generated by Django 3.2.7 on 2021-10-21 13:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0010_alter_employee_emp_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('grooming', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('punctuality', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('attire', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('teamwork', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('initiative', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('customer_service', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('performance', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employee')),
            ],
        ),
    ]
