# Generated by Django 3.2.7 on 2021-10-26 11:35

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='teamword',
        ),
        migrations.AddField(
            model_name='reviews',
            name='teamwork',
            field=models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Unacceptable'), (2, 'Needs Improvement'), (3, 'Satisfactory'), (4, 'Above Average'), (5, 'Exceptional')], default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviews',
            name='attendance',
            field=models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Unacceptable'), (2, 'Needs Improvement'), (3, 'Satisfactory'), (4, 'Above Average'), (5, 'Exceptional')]),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='attire',
            field=models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Unacceptable'), (2, 'Needs Improvement'), (3, 'Satisfactory'), (4, 'Above Average'), (5, 'Exceptional')]),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='grooming',
            field=models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Unacceptable'), (2, 'Needs Improvement'), (3, 'Satisfactory'), (4, 'Above Average'), (5, 'Exceptional')]),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='initiative',
            field=models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Unacceptable'), (2, 'Needs Improvement'), (3, 'Satisfactory'), (4, 'Above Average'), (5, 'Exceptional')]),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='productivity',
            field=models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Unacceptable'), (2, 'Needs Improvement'), (3, 'Satisfactory'), (4, 'Above Average'), (5, 'Exceptional')]),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='punctuality',
            field=models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Unacceptable'), (2, 'Needs Improvement'), (3, 'Satisfactory'), (4, 'Above Average'), (5, 'Exceptional')]),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='quality',
            field=models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Unacceptable'), (2, 'Needs Improvement'), (3, 'Satisfactory'), (4, 'Above Average'), (5, 'Exceptional')]),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='service',
            field=models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Unacceptable'), (2, 'Needs Improvement'), (3, 'Satisfactory'), (4, 'Above Average'), (5, 'Exceptional')]),
        ),
    ]
