# Generated by Django 3.2.7 on 2021-10-26 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20211026_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='created_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
