# Generated by Django 3.2.7 on 2021-10-26 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='Reminders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.CharField(blank=True, max_length=45, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=45, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employees')),
            ],
            options={
                'db_table': 'reminders',
            },
        ),
        migrations.CreateModel(
            name='TasksHasPositions',
            fields=[
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='taskEvents.tasks')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.positions')),
            ],
            options={
                'db_table': 'tasks_has_positions',
                'unique_together': {('task', 'position')},
            },
        ),
    ]
