# Generated by Django 3.2.7 on 2021-10-30 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('frequency', models.CharField(choices=[('SH_ST', 'Beginning of Shift'), ('SH_MD', 'Middle of Shift'), ('SH_EN', 'End of Shift'), ('D_ST', 'Start of Day'), ('D_MD', 'Middle of Day'), ('D_EN', 'End of Day'), ('WK_ST', 'Start of Week'), ('WK_MD', 'Middle of Week'), ('WK_EN', 'End of Week'), ('SH', 'Once Per Shift'), ('DLY', 'Once Per Day'), ('WKLY', 'Once Per Week'), ('MNTH', 'Once Per Month'), ('YRLY', 'Once Per Year'), ('QTLY', 'Once Per Yearly Quarter')], default='SH', max_length=5)),
                ('time_allocation', models.PositiveIntegerField(help_text='Appx. hours to complete')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.positions')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
