# Generated by Django 3.2.7 on 2021-10-30 17:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('taskEvents', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskshaspositions',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='taskshaspositions',
            name='position',
        ),
        migrations.RemoveField(
            model_name='taskshaspositions',
            name='task',
        ),
        migrations.AddField(
            model_name='tasks',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.positions'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='time_allocation',
            field=models.PositiveIntegerField(default=django.utils.timezone.now, help_text='Hours to complete'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasks',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.DeleteModel(
            name='Reminders',
        ),
        migrations.DeleteModel(
            name='TasksHasPositions',
        ),
    ]
