# Generated by Django 3.2.7 on 2021-11-02 20:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time_hr', models.TimeField(choices=[('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22')], verbose_name='In')),
                ('out_time_hr', models.TimeField(choices=[('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22')], verbose_name='Out')),
                ('position', models.CharField(blank=True, choices=[('1', 'Manager'), ('2', 'Assistant Manager'), ('3', 'Supervisor'), ('4', 'Server'), ('5', 'Busser'), ('6', 'Bartender'), ('7', 'Expo'), ('8', 'Host'), ('9', 'Barback'), ('20', 'Chef'), ('21', 'Sous Chef'), ('22', 'Pantry'), ('23', 'Line Cook'), ('24', 'Grill Cook'), ('25', 'Prep Cook'), ('26', 'Fry Cook'), ('27', 'Dishwasher')], max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedules.schedule')),
            ],
        ),
    ]
